title: Geffrey's Blog
email: geffrey.bos@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 My notes on personal knowledge management, product management, and technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://geffreys.blog/" # the base hostname & protocol for your site, e.g. http://example.com

highlighter: rouge
plugins:
  - jekyll-feed
  
permalink: /:title